#Configuration 'PersistenceVolumeClaim'(PVC) for  Mysql storage, dynamically provisioned by cluster
api version: v1
kind: PersistenceVolumeClaim
metadata:
  name: mysql-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    ReadWriteOnce # This specifies the mode of the claim that we are trying to create
  resources:
    requests:
      storage: 1Gi # This will tell kubernetes about the amount of space we are trying to claim
---
#Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
    app: mysql
    tier: database
  strategy:
    type: Recreate
    template:
      metadata:
        labels: # Must match 'service' and deployment selectors
        app: mysql
        tier: database
    spec:
      containers:
        image: mysql:5.7  # image from docker-hub
        args:
          "--ignore-db-dir=lost+found" # Workaround for https://github.com/docker-library/mysql/issues/186
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE # Setting Database Name from 'ConfigMap'
          value: kubernetes
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:  # Mounting volume obtained from Persistent Volume Claim
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql # This is the path in the container on which the mounting will take place
          volumes:
          - name: mysql-persistent-storage # Obtaining 'volume' from PVC
            persistentVolumeClaim:
              claimName: mysql-pv-claim
---
#Define a 'Service' GTo expose mysql to other services
apiVersion: v1
kind: Service
metadata:
  name: mysql # DNS name
  labels:
    app: mysql
    tier: database
spec:
  ports:
  - ports: 3306
    targetPort: 3306
selector:
    app: mysql
    tier: database
clusterIP: None # the Use DNS, Thus ClusterIP is not relevant





